### ISSUE TITLE
community page (to be fixed)

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/backend#340]
* promoter logo not loading on community page

I tried to get the URL and open it, and seems like, something is wrong.
IDK if this is be or fe.

![Image](https://user-images.githubusercontent.com/19441097/177540281-f6448347-b7c7-430a-a0ad-6e8c3bb08f56.png)

* managers on pending communities aren't loading

* ambassadors profile picture not loading

* zero beneficiaries result in infinite icon, should be -- and goal should also be --

![Image](https://user-images.githubusercontent.com/19441097/177648001-06adea37-2d16-4028-bb2c-5cb4c377032f.png)

**Comment by dev-jotape** [comment]
- [x] promoter logo not loading on community page
