### ISSUE TITLE
draft a plan for messages (structure, etc)

### ISSUE THREAD

**Issue by obernardovieira** [impactMarket/backend#356]
Requirements:
* country group (every user on a given country, once added as beneficiary, manager or ambassador, should be on that group) - no need to list members
* community group (every user that belongs to a community should be on that group) - no need to list members
* country management group (managers and ambassadors on a given country should be on that group) - should list members
* community management group (only ambassador and managers of that community) - should list members

Users on this groups should be automatically members of it, no need to do any action to join. They should not be able to leave.

**Comment by dev-jotape** [comment]
https://docs.google.com/document/d/1HIO3CKga4O-qWalzpEag_g9a9MILqqnNgBuHK1gyDcI/edit
