### ISSUE TITLE
Urgent: Communities deleted yesterday still showing up as one of our "Communities" - reported by Catarina

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/backend#594]
Yesterday, I deleted some communities in Brazil (approved and executed) but the same communities are showing up in the menu “Communities”

PC - GChrome

![image](https://github.com/impactMarket/support-issues/assets/127307303/196cc0fa-31d0-4e65-bf11-71a0876eb58d)
![image](https://github.com/impactMarket/support-issues/assets/127307303/43c26919-0ca4-4d9c-88ef-a0b1d39ebf21)

@obernardovieira

**Comment by obernardovieira** [comment]
@dev-jotape I guess the listener is still having issues.
